import { Inter } from "next/font/google";
import "./globals.css";
import { ItemsProvider } from "@/context/itemsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Intelligent Pantry Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ItemsProvider>{children}</ItemsProvider>
      </body>
    </html>
  );
}
